[project]
name = "download_files_by_map"
version = "1.1.0"
description = "download files using a json tree map"
authors = [
    {name = "Siak Hooi",email = "siakhooi@gmail.com"}
]
keywords = [ "downloader" ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Utilities"
]

license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests (>=2.32.3,<3.0.0)"
]

[project.urls]
homepage = "https://github.com/siakhooi/download-files-by-map"
repository = "https://github.com/siakhooi/download-files-by-map"
documentation = "https://github.com/siakhooi/download-files-by-map/wiki"
"Bug Tracker" = "https://github.com/siakhooi/download-files-by-map/issues"

[project.scripts]
download-files-by-map = 'download_files_by_map.cli:run'


[tool.poetry]
packages = [{include = "download_files_by_map", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^9.0.3"
pytest-cov = "^7.1.0"
flake8 = "^7.3.0"
pytest-responses = "^0.5.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
